---

- name: install zabbix-agent pre-requirements
  yum: name={{ item }}
    state=present
  with_items:
    - MySQL-python
    - zabbix22-agent
    - python-pip
  tags:
    - zabbix-agent

- name: update config zabbix-agent
  template:
    src=zabbix_agent.conf
    dest=/etc/zabbix_agent.conf
  notify: restart zabbix agent
  tags:
    - zabbix-agent

- name: update config zabbix-agentd
  template:
    src=zabbix_agentd.conf
    dest=/etc/zabbix_agentd.conf
  notify: restart zabbix agentd
  tags:
    - zabbix-agent

- name: start zabbix-agent
  service: name={{ item }}
    state=running
    enabled=yes
  with_items:
    - zabbix-agentd
    - zabbix-agent
  tags:
    - zabbix-agent
