---
- name: restart zabbix agent
  service: name=zabbix-agent state=restarted

- name: restart zabbix agentd
  service: name=zabbix-agentd state=restarted

- name: restart apache
  service: name=httpd state=restarted

